import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { MdToolbarModule } from '@angular/material';
import { RouterModule } from '@angular/router';

import { MaterialModules } from './material';
import { appRoutes } from './routes';
import { AppComponent } from './app.component';

/** services */
import { ToolbarMenuService } from './services/toolbar-menu.service';

/** auto generated by `ng generate component pages/$name` */
import { ToolbarComponent } from './pages/toolbar/toolbar.component';
// import { SidenavComponent } from './pages/sidenav/sidenav.component';
import { HomeComponent } from './pages/home/home.component';
import { PageNotFoundComponent } from './pages/page-not-found/page-not-found.component';
import { MicroTrainingComponent, MessageBoardDialogComponent } from './pages/micro-training/micro-training.component';
import { VideoLearningComponent } from './pages/video-learning/video-learning.component';
import { DocumentLearningComponent } from './pages/document-learning/document-learning.component';
import { VideoListComponent } from './pages/video-list/video-list.component';
import { VideoRecordsComponent } from './pages/video-records/video-records.component';
import { DocumentListComponent } from './pages/document-list/document-list.component';
import { DocumentRecordsComponent } from './pages/document-records/document-records.component';
import { DocumentStart2learnComponent } from './pages/document-start2learn/document-start2learn.component';
import { ActivityComponent } from './pages/activity/activity.component';
import { ActivityPartyComponent } from './pages/activity-party/activity-party.component';
import { ActivityDistributionComponent } from './pages/activity-distribution/activity-distribution.component';
import { ActivityMallComponent } from './pages/activity-mall/activity-mall.component';

@NgModule({
  declarations: [
    AppComponent,
    ToolbarComponent,
    // SidenavComponent,
    HomeComponent,
    PageNotFoundComponent,
    MicroTrainingComponent,
    MessageBoardDialogComponent,
    VideoLearningComponent,
    DocumentLearningComponent,
    VideoListComponent,
    VideoRecordsComponent,
    DocumentListComponent,
    DocumentRecordsComponent,
    DocumentStart2learnComponent,
    ActivityComponent,
    ActivityPartyComponent,
    ActivityDistributionComponent,
    ActivityMallComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(appRoutes),
    ...MaterialModules
  ],
  entryComponents: [MessageBoardDialogComponent],
  providers: [ToolbarMenuService],
  bootstrap: [AppComponent]
})
export class AppModule { }
